# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('archived_on', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(blank=True, max_length=1024)),
                ('location', models.IntegerField(db_index=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
